### ISSUE TITLE
Function to scan a directory of FCS files and rename to match $FIL keyword

### ISSUE THREAD

**Issue by gfinak** [RGLab/flowWorkspace#177]
Write a function to scan a directory of FCS files and rename those that don't match their $FIL keyword so that they do match their $FIL keyword.

**Comment by mikejiang** [comment]
Here is the new argument added to the parser:
* `searchByKeyword` ‘logical’: whether look up samples by
              their FCS keyword '$FIL' when the parser could not find
              them by FCS file name. (Sometime FCS file names could be
              altered but keyword preserves the original name). Default
              is TRUE.

**Comment by mikejiang** [comment]
`3.13.29` is pushed to bioc-devel , The `default` behavior is:
1. try to locate FCS by file name first
2. If failed, then try keyword `$FIL`

**Comment by mikejiang** [comment]
Maybe we should deprecate `searchByKeyword` argument.
The reason I exposed this `switch` to user was for the scenarios when searching by `FCS filename`  fails and then the **incorrect** `$FIL` keyword may gets matched instead. (which normally happens when `$FIL` keyword is in a generic form ,e.g `specimen_01`.)
But since we decided to use `additional.keys = '$TOT'` as a default validity check, we should be able to rule out this `false positive` situation. 
Besides, argument name  `searchByKeyword` itself is a bit misleading. So maybe deprecate it, @gfinak ?
