### ISSUE TITLE
extend getSingleCellExpression() to handle populations defined by multiple markers

### ISSUE THREAD

**Issue by ptvan** [RGLab/flowWorkspace#201]
During analyses I often need to condition cell populations (eg. cells that express at least 1 cytokine). For cell subsets defined by a single marker this is currently readily handled by supplying cytokine markers to `getSingleCellExpression()`'s `node` argument. However, some cell populations are defined by multiple markers (eg. Tfh == CXCR5+CXCR3-PD1+). @mikejiang helpfully suggested an extension to `getSingleCellExpression()` to handle these populations.

**Comment by mikejiang** [comment]
Currently `getSingleCellExpression` only does `boolean` operations on the already existing gated `population nodes` (i.e. `cytokine` gates). 

What @ptvan was thinking about is more generic use case: to apply these `cytokine` gates (or `thresholds`) on arbitrary `node` so that these `cytokine` marker expressions can be conditioned on any cell population other than the original parent. 

This will involve the geometrical gating , which is beyond what `getSingleCellExpression` can handle at this point. 

Right now,  @ptvan is simply `copying` these `cytokine` gates to the target node but the side effect is creating a bunch of temporary population nodes. Maybe what we really need is to have a way of applying gates to an arbitrary node without necessarily adding the children nodes.

**Comment by gfinak** [comment]
What I'm not a fan of about just applying gates without adding the nodes when extracting single-cell expression is that we lose traceability of how the data were generated (even if we have the code).
