### ISSUE TITLE
Some gates appearing in the wrong position

### ISSUE THREAD

**Issue by AngusNano** [RGLab/flowWorkspace#261]
Hi,

Thanks for your previous help with processing .wsp files.

However, I’ve hit another problem. Some (but not all) of the gates from my .wsp file appear in the wrong position, but I can’t work out why (see attached file). For example, analysing the Cont group in the attached file, the “Time gate” and “APC Cy7+” are in the correct position, but the “CD45.2+ blood leukocytes” gate is shifted to the right. Is there a transformation that I need to do on either the gate or the parameter?

Cheers

Angus

https://drive.google.com/open?id=1WOOqaixXOF7cJ7jCUQg5kxTwH7FKsOtr

**Comment by mikejiang** [comment]
Can you load it back to flowJo? I somehow couldn't reconnect wsp with FCS when I tried to check what the gates look like in flowJo
![image](https://user-images.githubusercontent.com/1385649/46558569-63d59900-c8a2-11e8-9f90-44c1c4b3d1dd.png)

**Comment by AngusNano** [comment]
Hi Mike,

Thanks for getting back to me so quickly. I have attached the .asc file which will hopefully work.

https://drive.google.com/open?id=1WO-wdvstIkugthiYqgljQthJag1_u059

On further investigation I think the problem is with the elliptical gates. I can switch to using polygon gates, but if there is an easy fix for the existing gating strategy that would be great.

Cheers

Angus

**Comment by mikejiang** [comment]
Indeed, the `ellipsoid` gate is not properly positioned
![image](https://user-images.githubusercontent.com/1385649/46633422-70582c80-cb02-11e8-9cdc-2b8a4b950d4a.png)
This may be related to #142 , not sure if the rules are lately changed or there is something special about `log`-transformed ellipsoid gate from flowJo?
Any idea, @jayalmarode, @jspidlen?

**Comment by jspidlen** [comment]
Hmm... I see that some of the ellipse gates appear out of place. I don't think we have changed anything relevant recently, but I seem to recall that there is (and has always been) a difference between how ellipse (vs. any other) gate types are saved, which could be the root of the issue. With ellipses, you need to get the transformation exactly right in order to have the gate in the right position and shape. With other gate types, if your transformation is a little bit off, the gate will still be "OK" (i.e., exact in the rectangular case and very close in the polygon case). This is due to the space in which the gates are being described.

**Comment by mikejiang** [comment]
It turns out the culprit is the incorrect parameter `T` (i.e. `top scale value`) of `flog` that creates the trouble for restoring the raw scale of the gate.
Here is the `log` transformation defined in `flowJo` 
```xml
<transforms:log transforms:offset="1"  transforms:decades="4" >
          <data-type:parameter data-type:name="Comp-405nm Qdot605 (615_30) LogH" />
</transforms:log>
```
based on the `flog` gating-ML standards, here is the `flowJo`'s variant
```
log10(x/T)/decades +  offset
```
Apparently `T` is not specified in `transform:log`, so we try to parse it from keyword `$PnR` based on the `FCS3.1`
>$PnR/n1/ [REQUIRED]
 this keyword specifies the maximum range,

```xml
        <Keyword name="$P25R"  value="65536" />
        <Keyword name="$P25N"  value="405nm Qdot605 (615_30) LogH" />
```
However, this data is already stored at `log` scale in FCS, based on keyword `$PnE`
```xml
        <Keyword name="$P25E"  value="4,1" />
```
 described in  the `FCS3.1`
>$PnE/f1,f2/
This keyword specifies whether parameter number n is stored on linear or logarithmic scale...
When logarithmic scale is used, the value of f1 specifies the number of logarithmic decades and
f2 represents the linear value that would have been obtained for a signal with a log value of 0

So we need to convert `$PnR` value from  logarithmic scale to linear scale in order to get the true value of `T` = `10^4 * 1 = 10000`. This is consistent with 
```xml
        <Keyword name="P25HI"  value="10000" />
        <Keyword name="P25LO"  value="1" />
```
However `P25HI` is NOT standard FCS keyword thus I would not rely on this source.

So @jspidlen was right, the polygon gates were not affected as much as Ellipse gate when transformation is a little off. But hopefully this fix will bring the stats even closer to `flowJo` for all gates.
@AngusNano pull the latest commit and let me know if it works for you.

**Comment by jspidlen** [comment]
Nice investigation work Mike!

**Comment by AngusNano** [comment]
Excellent, Mike. It works fine.

Thanks very much for your help.

Another note, in the README.md file there are a couple of typos. `library(BiocInstalller)` should be `library(BiocInstaller)`, `bicLite(flowWorkspace)` should be `biocLite(“flowWorkspace”)` and `install_github("flowWorkspace/RGLab", ref="trunk”)` should be `install_github("RGLab/flowWorkspace", ref="trunk")`
