### ISSUE TITLE
Opening FlowJo V10 WSP with no Gates

### ISSUE THREAD

**Issue by dubayc2** [RGLab/flowWorkspace#264]
Hello,
 
We are moving from FlowJo (FJ) V9 to V10. To do this we are creating FJ V10 workspaces with the set of FCS files we want to apply flowDensity (etc.) to for automated gating.
 
When we go to open these new FJ V10 .WSP files, they appear to open with flowWorkspace:
** 
> ws <- openWorkspace("NIRT03 W0 020618 Tcell.wsp")
> ws
FlowJo Workspace Version  20.0 
File location:  . 
File name:  NIRT03 W0 020618 Tcell.wsp 
Workspace is open. 
 Groups in Workspace
         Name Num.Samples
1 All Samples           3
> getSamples(ws)
  sampleID                                                  name  count
1        1    WBA 020618_T-Cell NIRT03 D0_T-Cell FM3_C02_001.fcs  99774
2        2 WBA 020618_T-Cell NIRT03 D0_T-Cell Test 1_C03_002.fcs 107801
3        3 WBA 020618_T-Cell NIRT03 D0_T-Cell Test 2_C04_003.fcs  89910
  pop.counts
1          0
2          0
3          0
** 

However when we look at gating (the list of groups of samples is blank):

** 
> gs <- parseWorkspace(ws,name = 1)
Error in .preprocessor(obj, ...) : Invalid sample group index.
> gs <- parseWorkspace(ws)
Choose which group of samples to import:
: 
Selection: 1
Enter an item from the menu, or 0 to exit
**
 
If we apply a single gate (any gate) to the .WSP and re-save it, flowWorkspace loads the .WSP.
 
Is there any reason not to have flowWorkspace just allow WSP Workspaces with zero gates to just load everything to a root 'gate'?
 
Thank you in advance for your time responding to this query...
 
Christopher
 
Other Info:
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS
flowWorkspace    "3.30.0"

**Comment by gfinak** [comment]
I think we can make this happen.

**Comment by dubayc2** [comment]
Cool!

Just one more edge case :0

Thanks...

Christopher

Christopher Dubay, PhD
Biomedical Informatics
Laboratory of Molecular and Tumor Immunology
Earle A. Chiles Research Institute
Providence Cancer Center
4805 NE Glisan St.- 2N57
Portland, OR 97213  USA
T: (503) 215-7981
F: (503) 215-6841

Christopher.dubay@providence.org<mailto:Christopher.dubay@providence.org>

**Comment by deborah-chasman** [comment]
I encountered the same issue -- trying to import a workspace with no gates and getting the error message "Error in .preprocessor(obj, ...) : Invalid sample group index." I figured out after reading this post and the source code that the error message means that the sample group table emptied out when it filtered out the ungated files. So the fix is to give parseWorkspace the argument "requiregates=F". 

Would it be possible to make the error message more descriptive? Something like  "Workspace contains no gated files. Perhaps you meant to use requiregates=F?" This would have been a big help for me as it's the first time I've worked with Flowjo workspaces.

Thanks a lot for considering!

**Comment by mikejiang** [comment]
Parsing samples that has no gates is now supported in latest `CytoML` trunk by switching on `include_empty_tree` flag. e.g.
```r
library(CytoML)
wsFile <- file.path(path, "no-gate.wsp")
ws <- open_flowjo_xml(wsFile)
gs <- flowjo_to_gatingset(ws, name = 1, include_empty_tree = TRUE)
gs_get_pop_paths(gs)
[1] "root"
```
