### ISSUE TITLE
update .travis.yml for cytoset branch

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#269]
To ensure `flowWorkspace/cytoset` branch builds and checks successfully on `Travis CI`

**Comment by jacobpwagner** [comment]
We just need to allow Travis access to the private `cytolib` repo. I think the easiest and most flexible way to do this might be to make a dedicated Github RGLab user account with read-access for CI purposes and then encrypt a GitHub PAT. Otherwise, we can encrypt a PAT for one of our accounts. @mikejiang, thoughts?

https://docs.travis-ci.com/user/private-dependencies/#dedicated-user-account
https://docs.travis-ci.com/user/encryption-keys/
