### ISSUE TITLE
Scale different between dot plots and getStats MFI

### ISSUE THREAD

**Issue by mfahlberg824** [RGLab/flowWorkspace#284]
Hi guys,

Sorry for so many questions! I'll get the hang of it eventually. But I have a new issue...

I'm able to successfully load and parse my FlowJo workspace, and make some nice dotplots:

![dotplots](https://user-images.githubusercontent.com/49100803/55371338-7af8ea80-54c3-11e9-988d-066bc3cd8d09.png)

The scale is correct there.

However, when I try to get the MFI of each channel, for some reason the scale changes. I should be seeing values >10,000. The same thing happens when I make a geom_density_ridge plot, the scale just goes from 0-200. I can't figure out what I'm doing wrong...any ideas?

Here's the code:

<img width="582" alt="Screen Shot 2019-04-01 at 9 22 38 PM" src="https://user-images.githubusercontent.com/49100803/55371583-56514280-54c4-11e9-800b-ee715b378d95.png">
<img width="584" alt="Screen Shot 2019-04-01 at 9 22 53 PM" src="https://user-images.githubusercontent.com/49100803/55371587-59e4c980-54c4-11e9-8493-4e1a670786db.png">

**Comment by gfinak** [comment]
That is because the data is stored transformed, and the axes on the plots are back-transformed to the raw scale for visualization. When you get the MFI, you get the transformed data. You would need to back-transform the data and compute the MFI.
Mike can point to the method to do that.
Generally we want to do so many operations on the transformed data (e.g., all the gating, clustering, or whatever) that it's more efficient computationally to store the transformed data.

**Comment by mikejiang** [comment]
You can use `getStats` API for that. See example https://github.com/RGLab/flowWorkspace/blob/trunk/R/getStats.R#L28

**Comment by mfahlberg824** [comment]
It worked, thanks! The other thing that worked for the density plots was transforming the GatingSet first.
