### ISSUE TITLE
write.FCS not working for cytoframe

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#308]
Currently `flowCore::write.FCS` only works for `flowFrame` but not for `cytoframe` due to its direct reference to s4 slot through `x@description` . There might be some reason for that, which needs to be investigated to see if it can be switched to more portable way through `keyword` or `description` methods.

**Comment by jacobpwagner** [comment]
It seems like it should be fairly manageable to switch it over to using `keyword`/`keyword<-` to be `cytoframe`-compatible. It just requires being a little careful because it seems to be depending on the partial replacement behavior of `description<-` for `flowFrame` so instead we just need to get the entire replacement set of keywords ready before the `keyword<-` call.

**Comment by jacobpwagner** [comment]
Link in the commit message didn't work, but `flowCore::write.FCS` should hopefully work for both `flowFrame` and `cytoframe` objects now: https://github.com/RGLab/flowCore/commit/eacda7f2847dc4b02495a639b4f156d60c13c489

**Comment by mikejiang** [comment]
It now passes all the existing testings (especially the subsetted cytoframes)
