### ISSUE TITLE
Problems Reading Spectral Flow FCS Files

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowWorkspace#317]
Hi @mikejiang & @jacobpwagner,

Sorry to bug you, I know that you are very busy!

I am having some issues reading in some spectral flow FCS files and I was hoping that you may have a solution.

I am able to load the files into a cytoset successfully using `load_cytoset_from_fcs` but get an error when trying to extract a `cytoframe`.

```{r}
cs[[1]]
Error in string_to_spill(txt) : 
  bad lexical cast: source type value could not be interpreted as target
```

Here is the traceback:
```{r}
11: stop(list(message = "bad lexical cast: source type value could not be interpreted as target", 
        call = string_to_spill(txt), cppstack = NULL))
10: string_to_spill(txt)
9: flowCore:::txt2spillmatrix(sp)
8: process_spill_keyword(desc)
7: .local(object, ...)
6: keyword(fr)
5: keyword(fr)
4: cytoframe_to_flowFrame(fr)
3: .local(x, i, j, ...)
2: cs[[1]]
1: cs[[1]]
```

It looks like it is related to the `spill` keyword? Not all files seem to be affected, I have attached a couple of problematic ones and one that works.

[Problematic FCS Files.zip](https://github.com/RGLab/flowWorkspace/files/4448554/Problematic.FCS.Files.zip)

[OK FCS Files.zip](https://github.com/RGLab/flowWorkspace/files/4448561/OK.FCS.Files.zip)

Appreciate your help!

Dillon

**Comment by jacobpwagner** [comment]
Not bugging at all. Thanks for bringing this to our attention. I found the issue. It looks like the C++ parser isn't handling the extra padding whitespaces in the `$SPILLOVER` value for the "bad" FCS files.

```
$SPILLOVER/22,B1-A,B2-A,B3-A,B4-A,B5-A,B6-A,B7-A,B8-A,B9-A,B10-A,B11-A,B12-A,B13-A,B14-A,R1-A,R2-A,R3-A,R4-A,R5-A,R6-A,R7-A,R8-A,                1,                0,                0,
```

I'll update the parser to handle those like `as.numeric` was doing in the R parser here:
https://github.com/RGLab/flowCore/blob/38f42215a8fc5692e04b4da7e095ae4bee1a6b6e/R/IO.R#L415
And I'll ping you when the fix is ready.

**Comment by jacobpwagner** [comment]
@DillonHammill , https://github.com/RGLab/cytolib/commit/2108e3c9038cfd8a4bb0623727a1fc38db529dd1 should fix it. Please pull and rebuild `cytolib` and `flowCore`. I don't think you'll need to rebuild `flowWorkspace` for this one because the change is handled by `flowCore::text2spillatrix`:
https://github.com/RGLab/flowWorkspace/blob/86fdb21985ea5c75f032ce443cb0ee600f9f5366/R/cytoframe.R#L493-L502

**Comment by DillonHammill** [comment]
Thanks @jacobpwagner! 

I am also having trouble updating the parameter names:
```{r}
colnames(cs) <- colnames(cs)
Error in set_all_channels(x@pointer, value) : 
  bad lexical cast: source type value could not be interpreted as target
```

Traceback:
```{r}
6: stop(list(message = "bad lexical cast: source type value could not be interpreted as target", 
       call = set_all_channels(x@pointer, value), cppstack = NULL))
5: set_all_channels(x@pointer, value)
4: `colnames<-`(`*tmp*`, value = value)
3: `colnames<-`(`*tmp*`, value = value)
2: `colnames<-`(`*tmp*`, value = c("Time", "FSC-H", "FSC-A", "SSC-H", 
   "SSC-A", "B1-A", "B2-A", "B3-A", "B4-A", "B5-A", "B6-A", "B7-A", 
   "B8-A", "B9-A", "B10-A", "B11-A", "B12-A", "B13-A", "B14-A", 
   "R1-A", "R2-A", "R3-A", "R4-A", "R5-A", "R6-A", "R7-A", "R8-A"
   ))
1: `colnames<-`(`*tmp*`, value = c("Time", "FSC-H", "FSC-A", "SSC-H", 
   "SSC-A", "B1-A", "B2-A", "B3-A", "B4-A", "B5-A", "B6-A", "B7-A", 
   "B8-A", "B9-A", "B10-A", "B11-A", "B12-A", "B13-A", "B14-A", 
   "R1-A", "R2-A", "R3-A", "R4-A", "R5-A", "R6-A", "R7-A", "R8-A"
   ))
```

**Comment by DillonHammill** [comment]
@jacobpwagner, I just read in the problematic files and trued to update the colnames.

I am away from my computer for a couple if hours, I will try re-buildibg flowWorkspace to see if that works.

**Comment by DillonHammill** [comment]
@jacobpwagner, this works with the latest flowWorkspace. Thanks for your help!
