### ISSUE TITLE
Provide mapping of resolved workspace sample id -> file path to parseWorkspace()

### ISSUE THREAD

**Issue by kevinkrouse** [RGLab/flowWorkspace#49]
I'd like to provide a mapping to parseWorkspace() of workspace samples to file paths that have been previously resolved by the user.  Currently parseWorkspace() will search the file system starting at the directory named by the path argument for FCS files.  However, the importer may have already resolved the files in a previous step.

**Comment by mikejiang** [comment]
#171 partially answers @gfinak's questions. Instead of adding a new `argument`, we can use existing `path` argument. 
* If it is a `scalar` character, parser uses it as the folder to search for `FCS`.
* If it is a `data.frame`, then use it as `mapping` between `sampleID` to `file path`(absolute), so no file system searching is needed. 

Potentially we can use `sampleID` as `guid` to label each `sample` in `GatingSet`, but it is probably not unique across `batches`(`xmls`). so the parser will still try `fcs name` first, if non-unique, then prompt user to supply `additional.keys` be be concatenated to `fcs filename`. (described in #171). But disk search will be avoided by this mapping.

**Comment by mikejiang** [comment]
@kevinkrouse, `mapping` is now supported in `flowWorkspace 3.13.14`
```r
mapping <- data.frame(sampleID = 19
                      , file = file.path(dataDir, "CytoTrol_CytoTrol_11.fcs")
                     )
gs <- parseWorkspace(ws, path = mapping, name = 4)
```
